### PR TITLE
Support Yarn/npm workspaces

### LINKED ISSUE #49: Support Yarn/npm workspaces
In my project, i'm using `yarn` workspaces.
It's my folder structure:

```
- api (subproject  - folder)
- app (subproject - folder)
- models (subproject - folder)
package.json
yarn.lock
```

When yarn is using workspaces, it creates a node_module folder at root directory with almost all dependencies of subprojects. Extensions is not identifying this behavior.

PS.: Realize that app (the project that has angular framework) has your own `package.json`, so it's the root directory too.

### PR DESCRIPTION
**Pull request by cyrilletuzi**
Fixes #49 

Should work with these `package.json` configs:

```json
{
  "workspaces": ["project1", "nested/project2"]
}
```

```json
{
  "workspaces": {
    "core": ["core/*"],
    "projects": ["projects/*"]
  }
}
```

Testing in real conditions is required. I've simulated these scenarios but I'm not a Yarn user myself.

Note: this PR has been done based on [npm specification](https://github.com/npm/rfcs/blob/de8d71c0453f5cf443d3ef2f47e313f12dd6aaf9/accepted/0000-workspaces.md), which follows the Yarn one.

To test:
- `git clone https://github.com/cyrilletuzi/vscode-angular-schematics.git`
- `cd vscode-angular-schematics`
- `git checkout packageworkspaces`
- `npm ci` (install)

Then 2 solutions:
1. directly debug via VS Code (third icon below the Explorer one on the left sidebar)
- it will be suggested when you open the project but you'll need to have [this VS Code extension](https://marketplace.visualstudio.com/items?itemName=eamodio.tsl-problem-matcher) installed and enabled
2. or package the extension:
- `npm install vsce -g`
- `vsce package`
- install the generated VSIX ([official VS Code instructions](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix))

### CODE REVIEW

**Comment by andreialecu** [comment]
@cyrilletuzi thanks for this!

I'm doing some testing, first thing I noticed is that the branch name is different, `packageworkspaces` not `yarnworkspaces`, is that correct?

Second. I noticed that indeed the explorer menu now includes the schematics commands inside my yarn workspace, on deep nested directories.

However, trying to add a service resulted in this error:
image

`@schematics/angular` is indeed under the root `node_modules`.

**Comment by andreialecu** [comment]
If you need a small repo to test with, this one uses yarn workspaces: https://github.com/andreialecu/ang9-ng6002

**Comment by cyrilletuzi** [comment]
Thanks for testing and the repo. I'll test with it tomorrow.

Can you go in the copy here the node_modules path the extension found? You can see it in "Angular schematics" output channel (second tab left to the Terminal).

> I'm doing some testing, first thing I noticed is that the branch name is different, packageworkspaces not yarnworkspaces, is that correct?

Yes, I had to do a new PR due to some Git mess, but forgot to update the testing steps. I updated the instructions.

Another: I just updated the PR as there was a major issue on Windows, please update.

**Comment by cyrilletuzi** [comment]
Can you also confirm me the exact location of `@schematics/angular` in the root workspace? Can't see this in the repo. Is it a direct child directory of `node_modules`, or in a subfolder?

**Comment by andreialecu** [comment]
I tested on an actual production project which is more complex. I'm not sure what that small repo is laid out like, I created it as a repro to an `angular` bug. It's possible the layout is different there.

**Comment by andreialecu** [comment]
> Can you also confirm me the exact location of `@schematics/angular` in the root workspace? Can't see this in the repo. Is it a direct child directory of `node_modules`, or in a subfolder?

In the production project it is a direct folder under `node_modules`. 
image

I'll try to test the new commit that fixed the windows bug in a couple of hours and will get back to you.

**Comment by andreialecu** [comment]
@cyrilletuzi I pulled the latest commits and the error persists.

I'm running on WSL (Ubuntu) via Windows 10 if it matters.

**Comment by andreialecu** [comment]
I stepped through a bit, findings:

image

`this.list` is `[]`

image

`fsPath` ends up `undefined` here. `workspaceFolder.name` is the root monorepo name, the `uri.path` seems to point to the subproject.

**Comment by andreialecu** [comment]
The if isn't entered because `packageJsonWorkspaces` is undefined:

image

The subproject has a `node_modules` itself, so this `if` is entered and I think it improperly gives up searching for the root.

image

As an idea, I think simply searching from the `workspaceRoot` of the currently opened vscode project might make sense, without trying to go up the directory tree. Usually the monorepo root would be the root of the vscode workspace itself.

**Comment by andreialecu** [comment]
For future proofing, especially considering that yarn also has a [PnP mode](https://classic.yarnpkg.com/en/docs/pnp/) that does not use `node_modules` at all, I think exposing an extension setting for overriding the path to `@angular/schematics` (maybe other schematics too) might also be a good idea.

**Comment by cyrilletuzi** [comment]
> The subproject has a `node_modules` itself

Is that normal? It is not what is explained [in official Yarn documentation](https://classic.yarnpkg.com/en/docs/workspaces/). Project-specific dependencies are supposed to be in `root/node_modules/project1/@angular/schematics`.

> I think simply searching from the workspaceRoot of the currently opened vscode project might make sense

Unfortunately it is not that simple, some people will open the Yarn workspace root and some others will open the Angular project folder directly.

**Comment by andreialecu** [comment]
@cyrilletuzi yes, because `root/node_modules/project1` is just a symlink to `packages/project`. 

From the link:
> Please note the fact that /workspace-a is aliased as /node_modules/workspace-a via a symlink.

So each subproject has its own `node_modules`, besides the main one. The root `node_modules` just lists shared/common dependencies, but in case of conflicts, subprojects will have different versions in their own `node_modules`

**Comment by andreialecu** [comment]
> directly



> Unfortunately it is not that simple, some people will open the Yarn workspace root and some others will open the Angular project folder directly.

It is unlikely that would even work properly.

With workspaces there is only one `yarn.lock` file at the root of the monorepo. 

It is definitely a bad practice to open just a subfolder in the repo and not the root, and not at all recommended.

However, it is possible that a monorepo has `ProjectA` at Angular 7 and `ProjectB` at Angular 9. In this case `@angular/schematics` would be both in `projecta/node_modules` and `projectb/node_modules`. 

The extension should know which one to use, and I think it already does based on this PR.

It just needs to keep going to parent folders until it finds `@angular/schematics`. Also relevant is this snippet from the [PnP](https://classic.yarnpkg.com/en/docs/pnp/) documentation:

> The way regular installs work is simple: Yarn generates a node_modules directory that Node is then able to consume. In this context, Node doesn’t know the first thing about what a package is: it only reasons in terms of files. “Does this file exist here? No? Let’s look in the parent node_modules then. Does it exist here? Still no? Too bad… parent folder it is!” - and it does this until it matches something that matches one of the possibilities.

**Comment by andreialecu** [comment]
Thinking about it, workspaces don't add anything special as far as the node environment is concerned. Everything still functions out of the box, `yarn` is not required at all for running a project created with workspaces.

Workspaces simply leverage the fact that `node_modules` resolution goes up the parent tree until it finds what it is looking for.

So in a way, I don't think it is relevant to parse the `package.json` to determine if it mentions workspaces or not. 

Simply improving dependency resolution to look up into parent `node_modules` folders should be all that is needed to get complete support. 

As a bonus, you could also add a way to override this path, like I mentioned earlier. Take a look at: 
https://yarnpkg.com/advanced/editor-sdks

There are extensions there which need to find `prettier` or `eslint` and Yarn v2 includes a CLI command to set it up properly. Basically it's just a workspace setting in the project. For typescript the setting is `tsserver.tsdk` and needs to be set to `.vscode/pnpify/typescript/lib`. That file is just a simple stub that is created by the yarn contributors, and it is likely someone might eventually create one for `vscode-angular-schematics`. In order to support that, the extension needs to have a way to override the path it looks for the schematics in.

**Pull request merged**
